#!/bin/bash
# Reorganize stories: replace "Components/X" with proper group/X
# All operations are on files in components/ui/

cd /tmp/ds-review

apply() {
  local old="$1"
  local new="$2"
  sed -i "s|title: '$old'|title: '$new'|" components/ui/*.stories.tsx 2>/dev/null
}

echo "=== Reorganizing story titles ==="

# === BUTTONS ===
apply "Components/Button" "Buttons/Button"
apply "Components/ButtonWithDropdown" "Buttons/ButtonWithDropdown"
apply "Components/FAB" "Buttons/FAB"
apply "Components/FABGroup" "Buttons/FABGroup"
apply "Components/HapticButton" "Buttons/HapticButton"
apply "Components/IconButton" "Buttons/IconButton"
apply "Components/SplitButton" "Buttons/SplitButton"

# === TYPOGRAPHY ===
apply "Components/Blockquote" "Typography/Blockquote"
apply "Components/Caption" "Typography/Caption"
apply "Components/CodeBlock" "Typography/CodeBlock"
apply "Components/Heading" "Typography/Heading"
apply "Components/Label" "Typography/Label"
apply "Components/Paragraph" "Typography/Paragraph"
apply "Components/Text" "Typography/Text"
apply "Components/Title" "Typography/Title"

# === FORMS ===
apply "Components/AddressSelector" "Forms/AddressSelector"
apply "Components/ChatInput" "Forms/ChatInput"
apply "Components/Combobox" "Forms/Combobox"
apply "Components/DatePicker" "Forms/DatePicker"
apply "Components/DateRangePicker" "Forms/DateRangePicker"
apply "Components/FileUpload" "Forms/FileUpload"
apply "Components/Input" "Forms/Input"
apply "Components/LoginForm" "Forms/LoginForm"
apply "Components/MarkdownEditor" "Forms/MarkdownEditor"
apply "Components/MultiFileUpload" "Forms/MultiFileUpload"
apply "Components/OTPInput" "Forms/OTPInput"
apply "Components/PasswordInput" "Forms/PasswordInput"
apply "Components/PromptSuggestionChips" "Forms/PromptSuggestionChips"
apply "Components/QuantitySelector" "Forms/QuantitySelector"
apply "Components/QueryBuilder" "Forms/QueryBuilder"
apply "Components/RatingInput" "Forms/RatingInput"
apply "Components/RichTextEditor" "Forms/RichTextEditor"
apply "Components/RotarySelector" "Forms/RotarySelector"
apply "Components/SearchInput" "Forms/SearchInput"
apply "Components/SegmentedInput" "Forms/SegmentedInput"
apply "Components/Select" "Forms/Select"
apply "Components/SignupForm" "Forms/SignupForm"
apply "Components/Slider" "Forms/Slider"
apply "Components/Switch" "Forms/Switch"
apply "Components/TagsInput" "Forms/TagsInput"
apply "Components/Textarea" "Forms/Textarea"
apply "Components/TimePicker" "Forms/TimePicker"
apply "Components/VoiceRecorder" "Forms/VoiceRecorder"
apply "Components/Checkbox" "Forms/Checkbox"
apply "Components/RadioGroup" "Forms/RadioGroup"
apply "Components/RangeSlider" "Forms/RangeSlider"

# === NAVIGATION ===
apply "Components/BottomNavigation" "Navigation/BottomNavigation"
apply "Components/BreadcrumbTabsHybrid" "Navigation/BreadcrumbTabsHybrid"
apply "Components/CommandMenu" "Navigation/CommandMenu"
apply "Components/DockBar" "Navigation/DockBar"
apply "Components/FilterBar" "Navigation/FilterBar"
apply "Components/FloatingToolbar" "Navigation/FloatingToolbar"
apply "Components/HamburgerMenuIcon" "Navigation/HamburgerMenuIcon"
apply "Components/MenuBar" "Navigation/MenuBar"
apply "Components/NavBar" "Navigation/NavBar"
apply "Components/NavigationDrawer" "Navigation/NavigationDrawer"
apply "Components/Pagination" "Navigation/Pagination"
apply "Components/ScrollProgressBar" "Navigation/ScrollProgressBar"
apply "Components/Sidebar" "Navigation/Sidebar"
apply "Components/Stepper" "Navigation/Stepper"
apply "Components/Tabs" "Navigation/Tabs"
apply "Components/ThemeToggle" "Navigation/ThemeToggle"
apply "Components/TopActionBar" "Navigation/TopActionBar"

# === OVERLAYS ===
apply "Components/ContextMenu" "Overlays/ContextMenu"
apply "Components/Modal" "Overlays/Modal"
apply "Components/ModalStackManager" "Overlays/ModalStackManager"
apply "Components/Popover" "Overlays/Popover"
apply "Components/Sheet" "Overlays/Sheet"
apply "Components/Tooltip" "Overlays/Tooltip"

# === SURFACES ===
apply "Components/Callout" "Surfaces/Callout"
apply "Components/ControlCenterToggles" "Surfaces/ControlCenterToggles"
apply "Components/EmptyState" "Surfaces/EmptyState"
apply "Components/GestureCard" "Surfaces/GestureCard"
apply "Components/ImmersiveHero" "Surfaces/ImmersiveHero"
apply "Components/InspectorPanel" "Surfaces/InspectorPanel"
apply "Components/LoadingOverlay" "Surfaces/LoadingOverlay"
apply "Components/MaintenanceMode" "Surfaces/MaintenanceMode"
apply "Components/NotificationCenterPanel" "Surfaces/NotificationCenterPanel"
apply "Components/OfflineState" "Surfaces/OfflineState"
apply "Components/Panel" "Surfaces/Panel"
apply "Components/ParallaxBanner" "Surfaces/ParallaxBanner"
apply "Components/Snackbar" "Surfaces/Snackbar"
apply "Components/WindowControls" "Surfaces/WindowControls"
apply "Components/WindowFrame" "Surfaces/WindowFrame"

# === FEEDBACK ===
apply "Components/AIThinkingIndicator" "Feedback/AIThinkingIndicator"
apply "Components/Alert" "Feedback/Alert"
apply "Components/Badge" "Feedback/Badge"
apply "Components/ConfirmDialog" "Feedback/ConfirmDialog"
apply "Components/Progress" "Feedback/Progress"
apply "Components/Skeleton" "Feedback/Skeleton"
apply "Components/Spinner" "Feedback/Spinner"
apply "Components/Toast" "Feedback/Toast"
apply "Components/NotificationBadge" "Feedback/NotificationBadge"

# === LAYOUT ===
apply "Components/Divider" "Layout/Divider"
apply "Components/Footer" "Layout/Footer"
apply "Components/GridSystem" "Layout/GridSystem"
apply "Components/Layout" "Layout/Layout"
apply "Components/MasonryLayout" "Layout/MasonryLayout"
apply "Components/ResizablePanel" "Layout/ResizablePanel"
apply "Components/ScrollArea" "Layout/ScrollArea"
apply "Components/SectionHeader" "Layout/SectionHeader"
apply "Components/Spacer" "Layout/Spacer"
apply "Components/SplitView" "Layout/SplitView"
apply "Components/StickyContainer" "Layout/StickyContainer"

# === DATA DISPLAY ===
apply "Components/Accordion" "Data Display/Accordion"
apply "Components/ActivityFeed" "Data Display/ActivityFeed"
apply "Components/ActivityMonitor" "Data Display/ActivityMonitor"
apply "Components/AgendaView" "Data Display/AgendaView"
apply "Components/AudioPlayer" "Data Display/AudioPlayer"
apply "Components/AvatarGroup" "Data Display/AvatarGroup"
apply "Components/BarcodeGenerator" "Data Display/BarcodeGenerator"
apply "Components/Calendar" "Data Display/Calendar"
apply "Components/Card" "Data Display/Card"
apply "Components/Chart" "Data Display/Chart"
apply "Components/ChatBubble" "Data Display/ChatBubble"
apply "Components/Chip" "Data Display/Chip"
apply "Components/Collapsible" "Data Display/Collapsible"
apply "Components/CommentThread" "Data Display/CommentThread"
apply "Components/Counters" "Data Display/Counters"
apply "Components/CountersListWithChart" "Data Display/CountersListWithChart"
apply "Components/DataGrid" "Data Display/DataGrid"
apply "Components/DefinitionList" "Data Display/DefinitionList"
apply "Components/DescriptionBlock" "Data Display/DescriptionBlock"
apply "Components/DeviceList" "Data Display/DeviceList"
apply "Components/DiffViewer" "Data Display/DiffViewer"
apply "Components/FileIntelligencePreview" "Data Display/FileIntelligencePreview"
apply "Components/Gallery" "Data Display/Gallery"
apply "Components/ImageCarousel" "Data Display/ImageCarousel"
apply "Components/ImageCropper" "Data Display/ImageCropper"
apply "Components/InfiniteHorizontalLoop" "Data Display/InfiniteHorizontalLoop"
apply "Components/JsonViewer" "Data Display/JsonViewer"
apply "Components/KPIBlock" "Data Display/KPIBlock"
apply "Components/KanbanBoard" "Data Display/KanbanBoard"
apply "Components/KeyValueInfo" "Data Display/KeyValueInfo"
apply "Components/Lightbox" "Data Display/Lightbox"
apply "Components/MessageReactions" "Data Display/MessageReactions"
apply "Components/PermissionsMatrix" "Data Display/PermissionsMatrix"
apply "Components/PriceDisplay" "Data Display/PriceDisplay"
apply "Components/PropertyList" "Data Display/PropertyList"
apply "Components/QRCodeGenerator" "Data Display/QRCodeGenerator"
apply "Components/RecoveryCodeDisplay" "Data Display/RecoveryCodeDisplay"
apply "Components/ResourceMonitor" "Data Display/ResourceMonitor"
apply "Components/Reviews" "Data Display/ReviewsRatings"
apply "Components/SchedulerTimeline" "Data Display/SchedulerTimeline"
apply "Components/ScrollRevealCards" "Data Display/ScrollRevealCards"
apply "Components/SecurityActivityLog" "Data Display/SecurityActivityLog"
apply "Components/SignaturePad" "Data Display/SignaturePad"
apply "Components/Sparkline" "Data Display/Sparkline"
apply "Components/StatisticDisplay" "Data Display/StatisticDisplay"
apply "Components/StickyImageTextSwap" "Data Display/StickyImageTextSwap"
apply "Components/Table" "Data Display/Table"
apply "Components/Tag" "Data Display/Tag"
apply "Components/Timeline" "Data Display/Timeline"
apply "Components/TreeView" "Data Display/TreeView"
apply "Components/VideoPlayer" "Data Display/VideoPlayer"

# === E-COMMERCE ===
apply "Components/CartPreview" "E-Commerce/CartPreview"
apply "Components/OrderSummary" "E-Commerce/OrderSummary"
apply "Components/ProductCard" "E-Commerce/ProductCard"

# === CYBERPUNK ===
apply "Components/ComicPanel" "Cyberpunk/ComicPanel"
apply "Components/FloatingElement" "Cyberpunk/FloatingElement"
apply "Components/InteractiveCursor" "Cyberpunk/InteractiveCursor"
apply "Components/UnscramblingText" "Cyberpunk/UnscramblingText"

# === INTERACTION / GESTURES ===
apply "Components/SlideToDelete" "Gestures/SlideToDelete"

# === FINTECH (components/ui that were already Fintech or should be) ===
# These already have Fintech/ prefix from earlier moves, just fixing inconsistency
apply "Components/CardSecurityControls" "Fintech/Cards/CardSecurityControls"
apply "Components/BalanceChart" "Fintech/Dashboard/BalanceChart"
apply "Components/BankAccountCard" "Fintech/Dashboard/BankAccountCard"
apply "Components/TransactionList" "Fintech/Dashboard/TransactionList"
apply "Components/FintechDashboardPreview" "Fintech/Dashboard/FintechDashboardPreview"
apply "Components/CashbackWidget" "Fintech/Cards/CashbackWidget"
apply "Components/CreditLimitManager" "Fintech/Credit & BNPL/CreditLimitManager"
apply "Components/EarlyPaymentDiscount" "Fintech/Credit & BNPL/EarlyPaymentDiscount"
apply "Components/InstallmentSimulator" "Fintech/Credit & BNPL/InstallmentSimulator"
apply "Components/CurrencyConverterWidget" "Fintech/FX & International Payments/CurrencyConverterWidget"
apply "Components/FairUseLimitTracker" "Fintech/FX & International Payments/FairUseLimitTracker"
apply "Components/AssetPriceTicker" "Fintech/Investments/AssetPriceTicker"
apply "Components/PortfolioDistribution" "Fintech/Investments/PortfolioDistribution"
apply "Components/BiometricPrompt" "Fintech/KYC/BiometricPrompt"
apply "Components/IdentityVerificationStep" "Fintech/KYC/IdentityVerificationStep"
apply "Components/SecurityOTPInput" "Fintech/KYC/SecurityOTPInput"
apply "Components/PaymentConfirmationModal" "Fintech/Payments/PaymentConfirmationModal"
apply "Components/PaymentMethodSelector" "Fintech/Payments/PaymentMethodSelector"
apply "Components/QuickTransferBar" "Fintech/Payments/QuickTransferBar"
apply "Components/TransferForm" "Fintech/Payments/TransferForm"
apply "Components/InteractiveBillSplitter" "Fintech/Social & P2P/InteractiveBillSplitter"
apply "Components/PeerTagInput" "Fintech/Social & P2P/PeerTagInput"
apply "Components/SocialPaymentFeed" "Fintech/Social & P2P/SocialPaymentFeed"
apply "Components/AssetAllocationChart" "Fintech/Wealth & Crypto/AssetAllocationChart"
apply "Components/RecurringInvestConfigurator" "Fintech/Wealth & Crypto/RecurringInvestConfigurator"
apply "Components/RetailSwapInterface" "Fintech/Wealth & Crypto/RetailSwapInterface"
apply "Components/InvoicePreview" "Fintech/Payments/InvoicePreview"
apply "Components/MultiCurrencyWallet" "Fintech/FX & International Payments/MultiCurrencyWallet"

# === ERROR HANDLING ===
apply "Components/ErrorBoundary" "Utils/ErrorBoundary"

# === PAGES ===
apply "Components/LandingPage" "Pages/LandingPage"

echo ""
echo "=== Verifying remaining Components/ titles ==="
remaining=$(grep -rn "title: 'Components/" components/ui/*.stories.tsx 2>/dev/null | grep -v __tests__ | wc -l)
echo "Remaining: $remaining"
if [ "$remaining" -gt 0 ]; then
  grep -rn "title: 'Components/" components/ui/*.stories.tsx 2>/dev/null | grep -v __tests__ | sed "s/.*'\([^']*\)'.*/\1/"
fi
